# Documentation Makefile

# Building of the doxygen documentation.
doc:
	doxygen docs/doxyfilerc
	echo "To open the documentation, type : "
	echo "		firefox html/index.html "
	echo "in your terminal." 

# Cleaning all built files
clean:
	rm -rf html